version: '3.8'

services:
  app:
    image: cehhghost/crosswords_backend:latest
    ports:
      - "8081:8081"  # Пробрасываем порт Spring Boot
    depends_on:
      - postgres
      - opensearch
    networks:
      - shared_network

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"  # Пробрасываем порт PostgreSQL
    environment:
      POSTGRES_DB: crossword_new
      POSTGRES_USER: crossword_new
      POSTGRES_PASSWORD: 1234567890
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared_network

  opensearch:
    image: opensearchproject/opensearch:2.11.0  # Используем OpenSearch вместо Elasticsearch
    ports:
      - "9200:9200"  # Пробрасываем порт OpenSearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: "false"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "CBsZ6#9kHxb"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISABLE_INSTALL_DEMO_CONFIG: "false"
      plugins.security.ssl.http.enabled: "true"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - shared_network

volumes:
  postgres-data:
  opensearch-data:
networks:
  shared_network:
    external: true