version: '3.8'

services:
  app:
    image: cehhghost/crosswords_backend:0.3.2-DEVELOPMENT
    ports:
      - "8081:8081"  # Пробрасываем порт Spring Boot
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    networks:
      - shared_network
    environment:
      OPENSEARCH_URIS: http://node-0.example.com:9200
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend-postgres:5432/crossword_new
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: ${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
      DEFAULT_ADMINS_PASSWORD: ${DEFAULT_ADMINS_PASSWORD}
      CREATE_SWAGGER: ${CREATE_SWAGGER}
      CROSSWORDS_FIREBASE_CREDENTIALS: ${CROSSWORDS_FIREBASE_CREDENTIALS}
      CROSSWORDS_FIREBASE_PROJECTID: ${CROSSWORDS_FIREBASE_PROJECTID}
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: crossword_new
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      shared_network:
        aliases:
          - backend-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  opensearch:
    image: opensearchproject/opensearch:2.19.2  # Используем OpenSearch вместо Elasticsearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: "false"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_PASSWORD}
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISABLE_INSTALL_DEMO_CONFIG: "false"
      plugins.security.ssl.http.enabled: "false"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      shared_network:
        aliases:
          - node-0.example.com
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS http://localhost:9200/_cat/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  postgres-data:
  opensearch-data:

networks:
  shared_network:
    external: true
