name: Docker Build and Push

on:
  push:
    branches:
      - main  # Триггер на изменения в ветке main

jobs:
  build-and-push:
    if: github.actor == 'cehhghost'
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Java (для сборки JAR)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Шаг 3: Сборка JAR-файла
      - name: Build JAR file
        run: mvn -f backend/pom.xml clean package -DskipTests

      # Шаг 4: Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 5: Авторизация в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 6: Получение версии из pom.xml (опционально)
      - name: Get version from pom.xml
        id: version
        run: |
          echo "VERSION=$(mvn -f backend/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      # Шаг 7: Сборка и публикация Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: backend # Контекст сборки - папка backend
          file: backend/Dockerfile # Явное указание Dockerfile
          push: true  # Публиковать образ после сборки
          tags: |
            cehhghost/crosswords_backend:latest
            cehhghost/crosswords_backend:${{ steps.version.outputs.VERSION }}
